name: Move Directories to Branches

on:
  push:
    branches: [main]

jobs:
  move-directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Move img directory to images branch
        run: |
          git checkout -b images || git checkout images
          mv img .
          git add .
          git commit -m "Move img directory to images branch"
          git push

      - name: Move json directory to json branch
        run: |
          git checkout -b json || git checkout json
          mv json .
          git add .
          git commit -m "Move json directory to json branch"
          git push
