name: Move Folders to Specific Branches

on:
  push:
    branches:
      - main

jobs:
  move-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Move img folder to images branch
        run: |
          if [ -d "img" ] && [ "$(ls -A img)" ]; then
            git checkout --orphan images
            git reset --hard
            git clean -fdx
            cp -r img/. .
            git add .
            git commit -m "Add img folder to images branch"
            git push --force origin images
          else
            echo "No img folder or img folder is empty; skipping images branch creation."
          fi

      - name: Switch back to main branch
        run: git checkout main

      - name: Move json folder to json branch
        run: |
          if [ -d "json" ] && [ "$(ls -A json)" ]; then
            git checkout --orphan json
            git reset --hard
            git clean -fdx
            cp -r json/. .
            git add .
            git commit -m "Add json folder to json branch"
            git push --force origin json
          else
            echo "No json folder or json folder is empty; skipping json branch creation."
          fi
