name: Move Folders to Branches

on:
  push:
    branches:
      - main

jobs:
  move-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Move img folder to images branch
        run: |
          git checkout --orphan images
          git reset --hard
          git add img
          git commit -m "Move img folder to images branch"
          git push --force origin images

      - name: Switch back to main branch
        run: git checkout main

      - name: Move json folder to json branch
        run: |
          git checkout --orphan json
          git reset --hard
          git add json
          git commit -m "Move json folder to json branch"
          git push --force origin json
